#ifndef ERR_H
#define ERR_H

#include <stdlib.h>
#include <stdio.h>

typedef enum {
    INVALID_MEMORY_ACCESS,
    INVALID_READ_ADDRESS,
    INVALID_WRITE_ADDRESS,
    INVALID_INSTRUCTION,
    INVALID_LOAD_ALIGNMENT,
    INVALID_STORE_ALIGNMENT,
    INVALID_INSTRUCTION_ALIGNMENT,
    ELF_OPEN_FAIL,
    ELF_HEADER_READ_FAIL,
    PROGRAM_HEADER_READ_FAIL,
    NOT_ELF_FILE,
    WRONG_ENDIAN_OR_SYSTEM,
    WRONG_ARCHITECTURE_OR_NOT_EXEC,
    ELF_IS_CORRUPTED,
    MEMORY_BOUNDS_HIT 
} err_code;

void report_and_abort(err_code error);

#endif