#ifndef ERR_H
#define ERR_H

#include <stdint.h>

typedef enum : uint8_t {
    INVALID_MEMORY_ACCESS = 100,
    INVALID_READ_ADDRESS = 101,
    INVALID_WRITE_ADDRESS = 102,

    INVALID_INSTRUCTION = 66,
    INVALID_LOAD_ALIGNMENT = 67,
    INVALID_STORE_ALIGNMENT = 68,
    INVALID_INSTRUCTION_ALIGNMENT = 69,

    ELF_OPEN_FAIL = 10,
    ELF_HEADER_READ_FAIL = 11,
    PROGRAM_HEADER_READ_FAIL = 12,
    NOT_ELF_FILE = 13,
    WRONG_ENDIAN_OR_SYSTEM = 14,
    WRONG_ARCHITECTURE_OR_NOT_EXEC = 15,
    ELF_IS_CORRUPTED = 16,
    MEMORY_BOUNDS_HIT = 17,
    LOAD_ELF_LSEEK_FAIL = 18,
    LOAD_SEGMENT_FAIL = 19,
    ELF_CLOSE_FAIL = 20,

    STACK_OVERFLOW = 150,
    SYSCALL_NOT_SUPPORTED = 155,

    EXIT_PROGRAM = 228,
    EXIT_RET_PROGRAM = 229
} err_code;

void report_and_abort(err_code error);

#endif